version: "3.8"

services:
  redis-node-1:
    image: redis:7.2-alpine
    container_name: kf-redis-cluster-node-1
    ports:
      - "7001:6379"
      - "17001:16379"
    environment:
      - HOST_IP=${HOST_IP:-127.0.0.1}
    command: >
      redis-server 
      --port 6379 
      --bind 0.0.0.0
      --cluster-enabled yes
      --cluster-config-file /data/nodes.conf
      --cluster-node-timeout 5000 
      --cluster-announce-ip ${HOST_IP:-127.0.0.1}
      --cluster-announce-port 7001
      --cluster-announce-bus-port 17001
      --appendonly yes
      --protected-mode no
    restart: unless-stopped

  redis-node-2:
    image: redis:7.2-alpine
    container_name: kf-redis-cluster-node-2
    ports:
      - "7002:6379"
      - "17002:16379"
    environment:
      - HOST_IP=${HOST_IP:-127.0.0.1}
    command: >
      redis-server 
      --port 6379 
      --bind 0.0.0.0
      --cluster-enabled yes
      --cluster-config-file /data/nodes.conf
      --cluster-node-timeout 5000 
      --cluster-announce-ip ${HOST_IP:-127.0.0.1}
      --cluster-announce-port 7002
      --cluster-announce-bus-port 17002
      --appendonly yes
      --protected-mode no
    restart: unless-stopped

  redis-node-3:
    image: redis:7.2-alpine
    container_name: kf-redis-cluster-node-3
    ports:
      - "7003:6379"
      - "17003:16379"
    environment:
      - HOST_IP=${HOST_IP:-127.0.0.1}
    command: >
      redis-server 
      --port 6379 
      --bind 0.0.0.0
      --cluster-enabled yes
      --cluster-config-file /data/nodes.conf
      --cluster-node-timeout 5000 
      --cluster-announce-ip ${HOST_IP:-127.0.0.1}
      --cluster-announce-port 7003
      --cluster-announce-bus-port 17003
      --appendonly yes
      --protected-mode no
    restart: unless-stopped
